openapi: 3.0.3
info:
  title: URL Shortener definition
  version: "0.1"
paths:
  /short_url:
    post:
      summary: Post a URL
      description: Post a URL and return a shortened url. If the URL exists, return existing shortened version.
      operationId: addShortUrl
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortUrlRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortUrl'
        '400':
          description: Invalid ID supplied
        '405':
          description: Validation exception
    get:
      summary: Get a URL
      description: Get a URL
      operationId: getShortUrl
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortUrl'
        '405':
          description: Invalid input
        '404':
          description: Url not found
components:
  schemas:
    ShortUrlRequest:
      type: object
      properties:
        url:
          type: string
          example: "yandex.ru/maps"
    ShortUrl:
      type: object
      properties:
        url:
          type: string
          example: "http://yandex.ru/maps"
        shortenUrl:
          type: string
          example: "http://bit.ly"
